//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalKeeper.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrystalKeeper.Core.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Keeper.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AutoAllGroup {
            get {
                return ResourceManager.GetString("AutoAllGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AutoFilterField {
            get {
                return ResourceManager.GetString("AutoFilterField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images.
        /// </summary>
        public static string AutoImagesField {
            get {
                return ResourceManager.GetString("AutoImagesField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string CaptionAbout {
            get {
                return ResourceManager.GetString("CaptionAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit templates....
        /// </summary>
        public static string CaptionEditTemplates {
            get {
                return ResourceManager.GetString("CaptionEditTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string CaptionImages {
            get {
                return ResourceManager.GetString("CaptionImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load database.
        /// </summary>
        public static string CaptionLoadDatabase {
            get {
                return ResourceManager.GetString("CaptionLoadDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load image.
        /// </summary>
        public static string CaptionLoadImage {
            get {
                return ResourceManager.GetString("CaptionLoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load images or movie.
        /// </summary>
        public static string CaptionLoadImagesOrMovie {
            get {
                return ResourceManager.GetString("CaptionLoadImagesOrMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string CaptionNewProject {
            get {
                return ResourceManager.GetString("CaptionNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save database.
        /// </summary>
        public static string CaptionSaveDatabase {
            get {
                return ResourceManager.GetString("CaptionSaveDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text.
        /// </summary>
        public static string CaptionTextbox {
            get {
                return ResourceManager.GetString("CaptionTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename item.
        /// </summary>
        public static string CaptionTextboxRename {
            get {
                return ResourceManager.GetString("CaptionTextboxRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above.
        /// </summary>
        public static string CmbxImageAnchorAbove {
            get {
                return ResourceManager.GetString("CmbxImageAnchorAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string CmbxImageAnchorLeft {
            get {
                return ResourceManager.GetString("CmbxImageAnchorLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string CmbxImageAnchorRight {
            get {
                return ResourceManager.GetString("CmbxImageAnchorRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under.
        /// </summary>
        public static string CmbxImageAnchorUnder {
            get {
                return ResourceManager.GetString("CmbxImageAnchorUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Images.
        /// </summary>
        public static string CmbxItemTypeEntryImages {
            get {
                return ResourceManager.GetString("CmbxItemTypeEntryImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink.
        /// </summary>
        public static string CmbxItemTypeHyperlink {
            get {
                return ResourceManager.GetString("CmbxItemTypeHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string CmbxItemTypeImages {
            get {
                return ResourceManager.GetString("CmbxItemTypeImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mineral Formula.
        /// </summary>
        public static string CmbxItemTypeMinFormula {
            get {
                return ResourceManager.GetString("CmbxItemTypeMinFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mineral Grouping.
        /// </summary>
        public static string CmbxItemTypeMinGrouping {
            get {
                return ResourceManager.GetString("CmbxItemTypeMinGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mineral Locality.
        /// </summary>
        public static string CmbxItemTypeMinLocality {
            get {
                return ResourceManager.GetString("CmbxItemTypeMinLocality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mineral Name.
        /// </summary>
        public static string CmbxItemTypeMinName {
            get {
                return ResourceManager.GetString("CmbxItemTypeMinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money (USD).
        /// </summary>
        public static string CmbxItemTypeMoneyUSD {
            get {
                return ResourceManager.GetString("CmbxItemTypeMoneyUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string CmbxItemTypeText {
            get {
                return ResourceManager.GetString("CmbxItemTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template: .
        /// </summary>
        public static string CollectionEditTemplate {
            get {
                return ResourceManager.GetString("CollectionEditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ConditionRemove {
            get {
                return ResourceManager.GetString("ConditionRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch column.
        /// </summary>
        public static string ContextMenuMoveColumn {
            get {
                return ResourceManager.GetString("ContextMenuMoveColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string ContextMenuRename {
            get {
                return ResourceManager.GetString("ContextMenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image.
        /// </summary>
        public static string DatabaseEditBackgroundImage {
            get {
                return ResourceManager.GetString("DatabaseEditBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DatabaseEditDefEditModeEdit {
            get {
                return ResourceManager.GetString("DatabaseEditDefEditModeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string DatabaseEditDefEditModeView {
            get {
                return ResourceManager.GetString("DatabaseEditDefEditModeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in.
        /// </summary>
        public static string DatabaseEditOpenModeA {
            get {
                return ResourceManager.GetString("DatabaseEditOpenModeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mode by default..
        /// </summary>
        public static string DatabaseEditOpenModeB {
            get {
                return ResourceManager.GetString("DatabaseEditOpenModeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localities.
        /// </summary>
        public static string DefaultTemplateCollectionLocalities {
            get {
                return ResourceManager.GetString("DefaultTemplateCollectionLocalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of localities..
        /// </summary>
        public static string DefaultTemplateCollectionLocalitiesDescription {
            get {
                return ResourceManager.GetString("DefaultTemplateCollectionLocalitiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minerals.
        /// </summary>
        public static string DefaultTemplateCollectionMinerals {
            get {
                return ResourceManager.GetString("DefaultTemplateCollectionMinerals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My mineral collection..
        /// </summary>
        public static string DefaultTemplateCollectionMineralsDescription {
            get {
                return ResourceManager.GetString("DefaultTemplateCollectionMineralsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string DefaultTemplateCollectionNotes {
            get {
                return ResourceManager.GetString("DefaultTemplateCollectionNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some miscellaneous notes..
        /// </summary>
        public static string DefaultTemplateCollectionNotesDescription {
            get {
                return ResourceManager.GetString("DefaultTemplateCollectionNotesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Location.
        /// </summary>
        public static string DefaultTemplateLocalitiesGpsLocation {
            get {
                return ResourceManager.GetString("DefaultTemplateLocalitiesGpsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string DefaultTemplateLocalitiesImages {
            get {
                return ResourceManager.GetString("DefaultTemplateLocalitiesImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality Name.
        /// </summary>
        public static string DefaultTemplateLocalitiesLocalityName {
            get {
                return ResourceManager.GetString("DefaultTemplateLocalitiesLocalityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string DefaultTemplateLocalitiesNotes {
            get {
                return ResourceManager.GetString("DefaultTemplateLocalitiesNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localities.
        /// </summary>
        public static string DefaultTemplateLocalitiesTitle {
            get {
                return ResourceManager.GetString("DefaultTemplateLocalitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Images.
        /// </summary>
        public static string DefaultTemplateMineralsExtraImages {
            get {
                return ResourceManager.GetString("DefaultTemplateMineralsExtraImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Location.
        /// </summary>
        public static string DefaultTemplateMineralsGpsLocation {
            get {
                return ResourceManager.GetString("DefaultTemplateMineralsGpsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string DefaultTemplateMineralsImages {
            get {
                return ResourceManager.GetString("DefaultTemplateMineralsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Value.
        /// </summary>
        public static string DefaultTemplateMineralsMarketValue {
            get {
                return ResourceManager.GetString("DefaultTemplateMineralsMarketValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string DefaultTemplateMineralsNotes {
            get {
                return ResourceManager.GetString("DefaultTemplateMineralsNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin / Location.
        /// </summary>
        public static string DefaultTemplateMineralsOriginLocation {
            get {
                return ResourceManager.GetString("DefaultTemplateMineralsOriginLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Chemical Formula.
        /// </summary>
        public static string DefaultTemplateMineralsPrimaryChemicalFormula {
            get {
                return ResourceManager.GetString("DefaultTemplateMineralsPrimaryChemicalFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Mineral Species.
        /// </summary>
        public static string DefaultTemplateMineralsPrimaryMineralSpecies {
            get {
                return ResourceManager.GetString("DefaultTemplateMineralsPrimaryMineralSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Mineral Species.
        /// </summary>
        public static string DefaultTemplateMineralsSecondaryMineralSpecies {
            get {
                return ResourceManager.GetString("DefaultTemplateMineralsSecondaryMineralSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species Group.
        /// </summary>
        public static string DefaultTemplateMineralsSpeciesGroup {
            get {
                return ResourceManager.GetString("DefaultTemplateMineralsSpeciesGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minerals.
        /// </summary>
        public static string DefaultTemplateMineralsTitle {
            get {
                return ResourceManager.GetString("DefaultTemplateMineralsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string DefaultTemplateNotesImages {
            get {
                return ResourceManager.GetString("DefaultTemplateNotesImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string DefaultTemplateNotesNotes {
            get {
                return ResourceManager.GetString("DefaultTemplateNotesNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string DefaultTemplateNotesTitle {
            get {
                return ResourceManager.GetString("DefaultTemplateNotesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be loaded because it is corrupted..
        /// </summary>
        public static string DlgCannotOpenCorrupt {
            get {
                return ResourceManager.GetString("DlgCannotOpenCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was not loaded because it was prevented from being loaded in that location..
        /// </summary>
        public static string DlgCannotOpenForRead {
            get {
                return ResourceManager.GetString("DlgCannotOpenForRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was not loaded because the location to load it in was changed while trying to load..
        /// </summary>
        public static string DlgCannotOpenNotFound {
            get {
                return ResourceManager.GetString("DlgCannotOpenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was not loaded because the filename is too long to process..
        /// </summary>
        public static string DlgCannotOpenTooLong {
            get {
                return ResourceManager.GetString("DlgCannotOpenTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be loaded for an unknown reason..
        /// </summary>
        public static string DlgCannotOpenUnknown {
            get {
                return ResourceManager.GetString("DlgCannotOpenUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be loaded because it is unrecognizable or not a Crystal Keeper file..
        /// </summary>
        public static string DlgCannotOpenUnrecognized {
            get {
                return ResourceManager.GetString("DlgCannotOpenUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is corrupt and cannot be saved..
        /// </summary>
        public static string DlgCannotSaveCorrupt {
            get {
                return ResourceManager.GetString("DlgCannotSaveCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was not saved because it was prevented from being saved in that location..
        /// </summary>
        public static string DlgCannotSaveForWrite {
            get {
                return ResourceManager.GetString("DlgCannotSaveForWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was not saved because the location to save it in was changed while trying to save..
        /// </summary>
        public static string DlgCannotSaveNotFound {
            get {
                return ResourceManager.GetString("DlgCannotSaveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was not saved because the filename is too long. Please use a shorter name..
        /// </summary>
        public static string DlgCannotSaveTooLong {
            get {
                return ResourceManager.GetString("DlgCannotSaveTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be saved. Try specifying a different location or filename..
        /// </summary>
        public static string DlgCannotSaveUnknown {
            get {
                return ResourceManager.GetString("DlgCannotSaveUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm closing the program.
        /// </summary>
        public static string DlgConfirmCloseCaption {
            get {
                return ResourceManager.GetString("DlgConfirmCloseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close and discard any unsaved changes?.
        /// </summary>
        public static string DlgConfirmCloseWarning {
            get {
                return ResourceManager.GetString("DlgConfirmCloseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        public static string DlgDeleteEntryCaption {
            get {
                return ResourceManager.GetString("DlgDeleteEntryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this entry will delete it everywhere. Continue?.
        /// </summary>
        public static string DlgDeleteEntryWarning {
            get {
                return ResourceManager.GetString("DlgDeleteEntryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This template is in use. Deleting this field will delete all entry data associated with it.
        ///
        ///The collections using this template are: .
        /// </summary>
        public static string DlgDeleteField {
            get {
                return ResourceManager.GetString("DlgDeleteField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template in use.
        /// </summary>
        public static string DlgDeleteFieldCaption {
            get {
                return ResourceManager.GetString("DlgDeleteFieldCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        public static string DlgDeleteImageCaption {
            get {
                return ResourceManager.GetString("DlgDeleteImageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the image?.
        /// </summary>
        public static string DlgDeleteImageWarning {
            get {
                return ResourceManager.GetString("DlgDeleteImageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deleting template.
        /// </summary>
        public static string DlgDeleteTemplateCaption {
            get {
                return ResourceManager.GetString("DlgDeleteTemplateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete this template. Are you sure?.
        /// </summary>
        public static string DlgDeleteTemplateNoEntries {
            get {
                return ResourceManager.GetString("DlgDeleteTemplateNoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This template is used by .
        /// </summary>
        public static string DlgDeleteTemplateWarningA {
            get {
                return ResourceManager.GetString("DlgDeleteTemplateWarningA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  collection(s). Deleting it will delete all associated collections. Are you sure?.
        /// </summary>
        public static string DlgDeleteTemplateWarningB {
            get {
                return ResourceManager.GetString("DlgDeleteTemplateWarningB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image too large.
        /// </summary>
        public static string DlgImageTooBigCaption {
            get {
                return ResourceManager.GetString("DlgImageTooBigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more files was larger than 2GB and couldn&apos;t be uploaded..
        /// </summary>
        public static string DlgImageTooBigWarning {
            get {
                return ResourceManager.GetString("DlgImageTooBigWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file couldn&apos;t be loaded or played correctly..
        /// </summary>
        public static string DlgMediaNotLoadedWarning {
            get {
                return ResourceManager.GetString("DlgMediaNotLoadedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create template?.
        /// </summary>
        public static string DlgNeedTemplateCaption {
            get {
                return ResourceManager.GetString("DlgNeedTemplateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A template must exist before you can create a collection. Would you like to create a template?.
        /// </summary>
        public static string DlgNeedTemplateWarning {
            get {
                return ResourceManager.GetString("DlgNeedTemplateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database.
        /// </summary>
        public static string DlgNewDatabaseCaption {
            get {
                return ResourceManager.GetString("DlgNewDatabaseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new database, discarding any unsaved changes?.
        /// </summary>
        public static string DlgNewDatabaseWarning {
            get {
                return ResourceManager.GetString("DlgNewDatabaseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project at .
        /// </summary>
        public static string DlgProjectNoLoadA {
            get {
                return ResourceManager.GetString("DlgProjectNoLoadA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  could not be loaded..
        /// </summary>
        public static string DlgProjectNoLoadB {
            get {
                return ResourceManager.GetString("DlgProjectNoLoadB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project at .
        /// </summary>
        public static string DlgProjectNotFoundA {
            get {
                return ResourceManager.GetString("DlgProjectNotFoundA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  could not be found..
        /// </summary>
        public static string DlgProjectNotFoundB {
            get {
                return ResourceManager.GetString("DlgProjectNotFoundB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string DlgTextboxSubmit {
            get {
                return ResourceManager.GetString("DlgTextboxSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type:.
        /// </summary>
        public static string FieldEditorDataType {
            get {
                return ResourceManager.GetString("FieldEditorDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this field with entries.
        /// </summary>
        public static string FieldEditorFieldInvisible {
            get {
                return ResourceManager.GetString("FieldEditorFieldInvisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show field name left of field.
        /// </summary>
        public static string FieldEditorFieldNameInline {
            get {
                return ResourceManager.GetString("FieldEditorFieldNameInline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the field name.
        /// </summary>
        public static string FieldEditorFieldNameInvisible {
            get {
                return ResourceManager.GetString("FieldEditorFieldNameInvisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images|*.bmp;*.jpg;*.jpeg;*.gif;*.tif;*.tiff;*.png.
        /// </summary>
        public static string FilterImages {
            get {
                return ResourceManager.GetString("FilterImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images or movie|*.bmp;*.jpg;*.jpeg;*.gif;*.tif;*.tiff;*.png;*.wmv;*.mp4.
        /// </summary>
        public static string FilterImagesOrMovie {
            get {
                return ResourceManager.GetString("FilterImagesOrMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to databases|*.mdat|all files|*.*.
        /// </summary>
        public static string FilterOpenSaveDatabase {
            get {
                return ResourceManager.GetString("FilterOpenSaveDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pictures|*.bmp;*.exif;*.gif;*.jpg;*.jpeg;*.png;*.ico;*.icon.
        /// </summary>
        public static string FilterPictures {
            get {
                return ResourceManager.GetString("FilterPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add entries that with any of the letters from .
        /// </summary>
        public static string GroupingEditByLetterA {
            get {
                return ResourceManager.GetString("GroupingEditByLetterA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to .
        /// </summary>
        public static string GroupingEditByLetterB {
            get {
                return ResourceManager.GetString("GroupingEditByLetterB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate conditions.
        /// </summary>
        public static string GroupingEditCondEval {
            get {
                return ResourceManager.GetString("GroupingEditCondEval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions to automatically add entries.
        /// </summary>
        public static string GroupingEditConditions {
            get {
                return ResourceManager.GetString("GroupingEditConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New condition.
        /// </summary>
        public static string GroupingEditCondNew {
            get {
                return ResourceManager.GetString("GroupingEditCondNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In group.
        /// </summary>
        public static string GroupingEditInGroup {
            get {
                return ResourceManager.GetString("GroupingEditInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in group.
        /// </summary>
        public static string GroupingEditNotInGroup {
            get {
                return ResourceManager.GetString("GroupingEditNotInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection description.
        /// </summary>
        public static string HintCollectionDescription {
            get {
                return ResourceManager.GetString("HintCollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string HintFilterSearch {
            get {
                return ResourceManager.GetString("HintFilterSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group is auto-generated and can&apos;t be edited..
        /// </summary>
        public static string HintGroupingNoEdit {
            get {
                return ResourceManager.GetString("HintGroupingNoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name a collection and press enter....
        /// </summary>
        public static string HintNewCollection {
            get {
                return ResourceManager.GetString("HintNewCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name an entry and press enter....
        /// </summary>
        public static string HintNewEntry {
            get {
                return ResourceManager.GetString("HintNewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of a new field....
        /// </summary>
        public static string HintNewField {
            get {
                return ResourceManager.GetString("HintNewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name a grouping and press enter....
        /// </summary>
        public static string HintNewGrouping {
            get {
                return ResourceManager.GetString("HintNewGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No collections have been created yet.
        /// </summary>
        public static string HintNoCollections {
            get {
                return ResourceManager.GetString("HintNoCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content to display.
        /// </summary>
        public static string HintNoContent {
            get {
                return ResourceManager.GetString("HintNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries have been added to this group.
        /// </summary>
        public static string HintNoEntries {
            get {
                return ResourceManager.GetString("HintNoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project description.
        /// </summary>
        public static string HintProjectDescription {
            get {
                return ResourceManager.GetString("HintProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here.
        /// </summary>
        public static string HintTextbox {
            get {
                return ResourceManager.GetString("HintTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MainDisplayFile {
            get {
                return ResourceManager.GetString("MainDisplayFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MainDisplayFileNew {
            get {
                return ResourceManager.GetString("MainDisplayFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MainDisplayFileOpen {
            get {
                return ResourceManager.GetString("MainDisplayFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string MainDisplayFileRecent {
            get {
                return ResourceManager.GetString("MainDisplayFileRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MainDisplayFileSave {
            get {
                return ResourceManager.GetString("MainDisplayFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string MainDisplayFileSaveAs {
            get {
                return ResourceManager.GetString("MainDisplayFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by:.
        /// </summary>
        public static string MainDisplayFilterBy {
            get {
                return ResourceManager.GetString("MainDisplayFilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MainDisplayHelp {
            get {
                return ResourceManager.GetString("MainDisplayHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainDisplayHelpAbout {
            get {
                return ResourceManager.GetString("MainDisplayHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MainDisplayHelpHelp {
            get {
                return ResourceManager.GetString("MainDisplayHelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Templates.
        /// </summary>
        public static string MainDisplayTemplates {
            get {
                return ResourceManager.GetString("MainDisplayTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        public static string MainDisplayTemplatesNew {
            get {
                return ResourceManager.GetString("MainDisplayTemplatesNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string NameUntitled {
            get {
                return ResourceManager.GetString("NameUntitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NewCollectionCancel {
            get {
                return ResourceManager.GetString("NewCollectionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Collection.
        /// </summary>
        public static string NewCollectionCaption {
            get {
                return ResourceManager.GetString("NewCollectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string NewCollectionDone {
            get {
                return ResourceManager.GetString("NewCollectionDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string NewCollectionTemplate {
            get {
                return ResourceManager.GetString("NewCollectionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewProjectNew {
            get {
                return ResourceManager.GetString("NewProjectNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string NewProjectOpen {
            get {
                return ResourceManager.GetString("NewProjectOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string NewProjectRecent {
            get {
                return ResourceManager.GetString("NewProjectRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pt.
        /// </summary>
        public static string RichtextFontPoint {
            get {
                return ResourceManager.GetString("RichtextFontPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TemplateEditorCancel {
            get {
                return ResourceManager.GetString("TemplateEditorCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center images at the top of each entry.
        /// </summary>
        public static string TemplateEditorCenterImages {
            get {
                return ResourceManager.GetString("TemplateEditorCenterImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content font color.
        /// </summary>
        public static string TemplateEditorContentFontColor {
            get {
                return ResourceManager.GetString("TemplateEditorContentFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete template.
        /// </summary>
        public static string TemplateEditorDeleteTemplate {
            get {
                return ResourceManager.GetString("TemplateEditorDeleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display up to.
        /// </summary>
        public static string TemplateEditorExtraImagesA {
            get {
                return ResourceManager.GetString("TemplateEditorExtraImagesA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extra images per entry.
        /// </summary>
        public static string TemplateEditorExtraImagesB {
            get {
                return ResourceManager.GetString("TemplateEditorExtraImagesB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extra images.
        /// </summary>
        public static string TemplateEditorExtraImagesBShort {
            get {
                return ResourceManager.GetString("TemplateEditorExtraImagesBShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string TemplateEditorFieldsTab {
            get {
                return ResourceManager.GetString("TemplateEditorFieldsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font:.
        /// </summary>
        public static string TemplateEditorFont {
            get {
                return ResourceManager.GetString("TemplateEditorFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string TemplateEditorFontSection {
            get {
                return ResourceManager.GetString("TemplateEditorFontSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra images.
        /// </summary>
        public static string TemplateEditorImageAnchorA {
            get {
                return ResourceManager.GetString("TemplateEditorImageAnchorA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the main image.
        /// </summary>
        public static string TemplateEditorImageAnchorB {
            get {
                return ResourceManager.GetString("TemplateEditorImageAnchorB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main image.
        /// </summary>
        public static string TemplateEditorImageAnchorBShort {
            get {
                return ResourceManager.GetString("TemplateEditorImageAnchorBShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string TemplateEditorImagesSection {
            get {
                return ResourceManager.GetString("TemplateEditorImagesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries use one column.
        /// </summary>
        public static string TemplateEditorOneColumn {
            get {
                return ResourceManager.GetString("TemplateEditorOneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string TemplateEditorOrganizationSection {
            get {
                return ResourceManager.GetString("TemplateEditorOrganizationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string TemplateEditorSaveChanges {
            get {
                return ResourceManager.GetString("TemplateEditorSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TemplateEditorSettingsTab {
            get {
                return ResourceManager.GetString("TemplateEditorSettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title font color.
        /// </summary>
        public static string TemplateEditorTitleFontColor {
            get {
                return ResourceManager.GetString("TemplateEditorTitleFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries use two columns.
        /// </summary>
        public static string TemplateEditorTwoColumns {
            get {
                return ResourceManager.GetString("TemplateEditorTwoColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Joshua Lamusga, 2016.
        /// </summary>
        public static string TipAboutCopyright {
            get {
                return ResourceManager.GetString("TipAboutCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Keeper was developed as a free program for mineral collectors and hobbyists to store their mineral information in a convenient database with a neat and modern display..
        /// </summary>
        public static string TipAboutDescription {
            get {
                return ResourceManager.GetString("TipAboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Version 1.0 ---.
        /// </summary>
        public static string TipAboutVersion {
            get {
                return ResourceManager.GetString("TipAboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image link wasn&apos;t found -- click to locate or reset image..
        /// </summary>
        public static string TipBrokenImage {
            get {
                return ResourceManager.GetString("TipBrokenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to delete all images..
        /// </summary>
        public static string TipBttnDelete {
            get {
                return ResourceManager.GetString("TipBttnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to toggle volume muting for movies..
        /// </summary>
        public static string TipBttnMute {
            get {
                return ResourceManager.GetString("TipBttnMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to upload or change images..
        /// </summary>
        public static string TipBttnUpload {
            get {
                return ResourceManager.GetString("TipBttnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to upload a movie or frames for an animation..
        /// </summary>
        public static string TipBttnUploadMovie {
            get {
                return ResourceManager.GetString("TipBttnUploadMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A short description about the collection..
        /// </summary>
        public static string TipCollectionEditDescription {
            get {
                return ResourceManager.GetString("TipCollectionEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the type of data of the selected field..
        /// </summary>
        public static string TipFieldEditorDataType {
            get {
                return ResourceManager.GetString("TipFieldEditorDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the selected field down so it displays closer to the bottom..
        /// </summary>
        public static string TipFieldEditorMoveDown {
            get {
                return ResourceManager.GetString("TipFieldEditorMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the selected field to the first column for display..
        /// </summary>
        public static string TipFieldEditorMoveLeft {
            get {
                return ResourceManager.GetString("TipFieldEditorMoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the selected field to the first column for display..
        /// </summary>
        public static string TipFieldEditorMoveRight {
            get {
                return ResourceManager.GetString("TipFieldEditorMoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the selected field up so it displays closer to the top..
        /// </summary>
        public static string TipFieldEditorMoveUp {
            get {
                return ResourceManager.GetString("TipFieldEditorMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of data to store in the new field..
        /// </summary>
        public static string TipFieldEditorNewDataType {
            get {
                return ResourceManager.GetString("TipFieldEditorNewDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For fast navigation, only show some entries by filtering out others..
        /// </summary>
        public static string TipMainDisplayFilter {
            get {
                return ResourceManager.GetString("TipMainDisplayFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a name and press enter to make a collection..
        /// </summary>
        public static string TipMainDisplayNewCollection {
            get {
                return ResourceManager.GetString("TipMainDisplayNewCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a name and press enter to make an entry..
        /// </summary>
        public static string TipMainDisplayNewEntry {
            get {
                return ResourceManager.GetString("TipMainDisplayNewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a name and press enter to make a grouping..
        /// </summary>
        public static string TipMainDisplayNewGroup {
            get {
                return ResourceManager.GetString("TipMainDisplayNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to print the page..
        /// </summary>
        public static string TipMainDisplayPrint {
            get {
                return ResourceManager.GetString("TipMainDisplayPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to switch between edit and display mode..
        /// </summary>
        public static string TipMainDisplayToggleEdit {
            get {
                return ResourceManager.GetString("TipMainDisplayToggleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates define how entries are displayed and what they store..
        /// </summary>
        public static string TipNewCollectionTemplate {
            get {
                return ResourceManager.GetString("TipNewCollectionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle bold effect..
        /// </summary>
        public static string TipRichtextBold {
            get {
                return ResourceManager.GetString("TipRichtextBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to set the text color..
        /// </summary>
        public static string TipRichtextFontColor {
            get {
                return ResourceManager.GetString("TipRichtextFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to set the font family..
        /// </summary>
        public static string TipRichtextFontFamily {
            get {
                return ResourceManager.GetString("TipRichtextFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to set the text size..
        /// </summary>
        public static string TipRichtextFontSize {
            get {
                return ResourceManager.GetString("TipRichtextFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle italic effect..
        /// </summary>
        public static string TipRichtextItalic {
            get {
                return ResourceManager.GetString("TipRichtextItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle strikethrough..
        /// </summary>
        public static string TipRichtextStrikethrough {
            get {
                return ResourceManager.GetString("TipRichtextStrikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle underlining..
        /// </summary>
        public static string TipRichtextUnderline {
            get {
                return ResourceManager.GetString("TipRichtextUnderline", resourceCulture);
            }
        }
    }
}
