//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalKeeper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrystalKeeper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abakusz-kő||||0
        ///Abellaite||NaPb_2_(CO_3_)_2_(OH)|Spain|1
        ///Abelsonite||NiC_31_H_32_N_4_|USA|1
        ///Abenakiite-(Ce)||Na_26_Ce_6_(SiO_3_)_6_(PO_4_)_6_(CO_3_)_6_(SO_2_)O|Canada|1
        ///Abernathyite|Natroautunite group|K(UO_2_)AsO_4_·3H_2_O|USA|1
        ///Abhurite||Sn^2+^_21_O_6_(OH)_14_Cl_16_|Saudi Arabia|1
        ///Ablykite||||0
        ///Abramovite||Pb_2_SnInBiS_7_|Russia|1
        ///Abrazite||||0
        ///Absarokite||||0
        ///Absite||Ti_7_U_2_ThO_20_·5H_2_0|Australia|0
        ///Abswurmbachite|Braunite group|Cu^2+^Mn^3+^_6_O_8_(SiO_4_)|Greece|1
        ///Abuite||CaAl_2_(PO_4_)_2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Minerals {
            get {
                return ResourceManager.GetString("Minerals", resourceCulture);
            }
        }
    }
}
